version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "@openzeppelin/contracts"
      - dependency-name: "@openzeppelin/contracts-upgradeable"
